### PR TITLE
Added capability for .remote() to contact the DHT (BEP46)

### PR DESCRIPTION
**Pull request by lmatteis**
Discussion here https://github.com/feross/webtorrent/issues/886#issuecomment-241189570

### CODE REVIEW

**Comment by lmatteis** [comment]
@yciabaud fixed the travis issue, but now the `test-browser` fails, which btw also fails locally. Seems a credentials problem with saucelabs.

**Comment by lmatteis** [comment]
poke @feross

**Comment by feross** [comment]
Sorry traveling in China for another week with sparse Internet. Will check
this out when I get back.

**Comment by HostFat** [comment]
Any news on this?

**Comment by jabyrd3** [comment]
Just want to sub to this so I can get an update whenever he's around.

**Comment by lmatteis** [comment]
@feross any news on this? The test errors are because of saucelabs credentials.

**Comment by matthewaveryusa** [comment]
@feross @lmatteis is this just a matter of adding the following snippit at the beginning of test.js
```
var runSauceLabs = !process.env.CI ||
  (process.env.SAUCE_USERNAME && process.env.SAUCE_ACCESS_KEY)

if(!runSauceLabs) { process.exit(0); }
```

I think it's related to this: https://github.com/defunctzombie/zuul/issues/86

I also noticed that the travis link is broken. It points to feross/... but the actual location is webtorrent/...

**Comment by matthewaveryusa** [comment]
Well, a bit more than that. Basically copying what is done in webtorrent/package.json to short-circuit the sauce issue for PRs. I can submit a separate PR to do this if that's what's needed to unblock this PR.

**Comment by matthewaveryusa** [comment]
submitted https://github.com/webtorrent/parse-torrent/pull/46 for what I mentioned above. Should be all squared away

**Comment by RangerMauve** [comment]
Have the CI issues been fixed since this was created? Would a new PR that adds this functionality be welcome?

**Comment by RangerMauve** [comment]
@DiegoRBaquero Was this closed because it's been implemented? Or is it just very out of date?

**Comment by DiegoRBaquero** [comment]
Closed in favor of #58

**Comment by RangerMauve** [comment]
Thank you for clarifying!

**Pull request closed without merging**
